parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - unicorn
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:unicorn/recommended
env:
  browser: true
  node: true
  es6: true
rules:
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-var-requires': off
  unicorn/prefer-ternary: off
  unicorn/no-array-reduce: off
  unicorn/filename-case:
    - error
    - cases:
        kebabCase: true
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        args: true
